version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
    labels:
    - "dependencies"
    - "actions"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
    labels:
    - "dependencies"
