run:
  deadline: 10m
  tests: false
  skip-dirs:
  - bin
  - build
  - tools

linters:
  disable-all: true
  enable:
  - gofmt
  - govet
  - revive
  - errcheck
  - unconvert
  - staticcheck
  - ineffassign
  - unparam
  - unused
  - misspell

issues:
  exclude-use-default: false

  exclude-rules:
  # https://staticcheck.io/docs/checks#SA9004
  - linters: [staticcheck]
    text: 'SA9004:'

  - linters: [unparam]
    text: '`_[^`]*` is unused'

  - linters: [unparam]
    path: '(_test.go|.pb.go|_gen.go)'

  - linters: [revive]
    text: 'package-comments'

linters-settings:
  gofmt:
    simplify: true
  errcheck:
    check-type-assertions: false
  govet:
    check-shadowing: false
