name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true

    - uses: actions/github-script@v6
      id: tag
      with:
        result-encoding: string
        script: |
          return context.payload.ref.replace(/refs\/tags\/v/, '');

    - uses: actions/github-script@v6
      id: time
      with:
        result-encoding: string
        script: |
          return Math.round((new Date()).getTime() / 1000);

    - uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_TIME: ${{ steps.time.outputs.result }}
        VERSION: ${{ steps.tag.outputs.result }}
