name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - uses: actions/github-script@v7
      id: tag
      with:
        result-encoding: string
        script: |
          return context.payload.ref.replace(/refs\/tags\/v/, '');

    - uses: actions/github-script@v7
      id: time
      with:
        result-encoding: string
        script: |
          return Math.round((new Date()).getTime() / 1000);

    - uses: goreleaser/goreleaser-action@v6.3.0
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_TIME: ${{ steps.time.outputs.result }}
        VERSION: ${{ steps.tag.outputs.result }}
