name: reviewdog

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'tools/**'
    - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: true
          level: error
